In [2]:
import numpy as np

In [3]:
accelo = np.zeros((10, 3))
freq = 5
accelo

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
accelo_reps = [accelo[i:i + freq] for i in range(0, len(accelo), freq)]
accelo_reps[0]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
n_steps = accelo_reps[0].shape[0]
blah = np.zeros((n_steps, 6))
blah[0]

array([0., 0., 0., 0., 0., 0.])